/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-01-14 09:04:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mariadb.design_005falbum1;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import AlbumBeans.Design_album01DAO;
import AlbumBeans.Design_album01TO;

public final class board_005fview1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("AlbumBeans.Design_album01DAO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("AlbumBeans.Design_album01TO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");
	String seq = request.getParameter("seq");
	String cpage = request.getParameter("cpage");

	Design_album01TO to = new Design_album01TO();
	to.setSeq(seq);

	Design_album01DAO dao = new Design_album01DAO();

	ArrayList<Design_album01TO> toLists = new ArrayList<Design_album01TO>();
	toLists = dao.board_view1(seq);

	String subject = toLists.get(0).getSubject();
	String writer = toLists.get(0).getWriter();
	String content = toLists.get(0).getContent();

	content.replaceAll("\n", "<br>");

	String[] mail = new String[2];
	if (!toLists.get(0).getMail().equals("")) {
		mail = toLists.get(0).getMail().split("@");
	} else {
		mail[0] = "";
		mail[1] = "";
	}
	String filename_ch = "";
	if (!toLists.get(0).getFilename_ch().equals("")) {
		filename_ch = "<img src='../../upload/" + toLists.get(0).getFilename_ch()
				+ "' width='900' onerror='' /><br/>";
	}
	String hit = toLists.get(0).getHit();
	String wdate = toLists.get(0).getWdate();

	String com_writer = "";
	String com_comment = "";
	String com_date = "";
	String cseq = "";

	StringBuffer sbHTML = new StringBuffer();

	for (int i = 1; i < toLists.size(); i++) {
		com_writer = toLists.get(i).getCom_writer();
		com_comment = toLists.get(i).getCom_comment();
		com_date = toLists.get(i).getCom_date();
		cseq = toLists.get(i).getCseq();

		sbHTML.append("<tr>");
		sbHTML.append("<td class='coment_re' width=''><strong>" + com_writer + "</strong>");
		sbHTML.append(" (" + com_date + ")");
		sbHTML.append("<div class='coment_re_txt'>" + com_comment + "</div></td>");

		// 댓글삭제부분
		sbHTML.append("<td class='coment_re' width='12%' align='right'>");

		sbHTML.append("<form action='board_reply_delete_ok.jsp' name='delcomment' method='post' onsubmit='return comdel(" + cseq + ")'>");

		sbHTML.append("<input type='hidden' name='seq' value='" + seq + "'>");
		sbHTML.append("<input type='hidden' name='cpage' value='" + cpage + "'>");
		sbHTML.append("<input type='hidden' name='cseq' value='" + cseq + "'>");

		sbHTML.append("		<input type='password' id='" + cseq
				+ "pas' name='" + cseq + "password' class='coment_input pR10' value='' />'");
		sbHTML.append("		<input type='image' src='../../images/icon_del.gif' alt='삭제' style='vertical-align: middle' />");
		sbHTML.append("</form>");
		sbHTML.append("</td>");

		sbHTML.append("</tr>");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../css/board_view.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\twindow.onload = function() {\r\n");
      out.write("\t\tdocument.cfrm.cbutton.onclick = function() {\r\n");
      out.write("\t\t\tif (document.cfrm.cwriter.value.trim() == '') {\r\n");
      out.write("\t\t\t\talert('글쓴이를 입력해 주세요.')\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (document.cfrm.cpassword.value.trim() == '') {\r\n");
      out.write("\t\t\t\talert('비밀번호를 입력해 주세요.')\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.cfrm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar comdel = function(cseq) {\r\n");
      out.write("\t\tvar x = document.getElementById(cseq + 'pas').value\r\n");
      out.write("\t\tif(x == '') {\r\n");
      out.write("\t\t\talert('댓글을 삭제하려면 비밀번호를 입력해 주세요.');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 상단 디자인 -->\r\n");
      out.write("\t<div class=\"contents1\">\r\n");
      out.write("\t\t<div class=\"con_title\">\r\n");
      out.write("\t\t\t<p style=\"margin: 0px; text-align: right\">\r\n");
      out.write("\t\t\t\t<img style=\"vertical-align: middle\" alt=\"\"\r\n");
      out.write("\t\t\t\t\tsrc=\"../../images/home_icon.gif\" /> &gt; 커뮤니티 &gt; <strong>여행지리뷰</strong>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"contents_sub\">\r\n");
      out.write("\t\t\t<!--게시판-->\r\n");
      out.write("\t\t\t<div class=\"board_view\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"10%\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"60%\">");
      out.print(subject);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"10%\">등록일</th>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"20%\">");
      out.print(wdate);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>글쓴이</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(writer);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<th>조회</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(hit);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" height=\"200\" valign=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"padding: 20px; line-height: 160%\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"bbs_file_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(filename_ch);
      out.write("<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div> ");
      out.print(content);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t");
      out.print(sbHTML);
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"board_reply_ok.jsp\" method=\"post\" name=\"cfrm\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(seq);
      out.write("\" name=\"seq\"> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"hidden\" value=\"");
      out.print(cpage);
      out.write("\" name=\"cpage\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"94%\" class=\"coment_re\">글쓴이 <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"cwriter\" maxlength=\"5\" class=\"coment_input\" />&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t비밀번호 <input type=\"password\" name=\"cpassword\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"coment_input pR10\" />&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"6%\" class=\"bg01\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"bg01\"><textarea name=\"ccontent\" cols=\"\" rows=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"coment_input_text\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\" class=\"bg01\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"cbutton\" type=\"button\" class=\"btn_re btn_txt01\">댓글등록</button>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"btn_area\">\r\n");
      out.write("\t\t\t\t<div class=\"align_left\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn_list btn_txt02\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"cursor: pointer;\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='board_list1.jsp?cpage=");
      out.print(cpage);
      out.write("'\">목록</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"align_right\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn_list btn_txt02\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"cursor: pointer;\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='board_modify1.jsp?seq=");
      out.print(seq);
      out.write("&cpage=");
      out.print(cpage);
      out.write("'\">수정</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn_list btn_txt02\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"cursor: pointer;\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='board_delete1.jsp?seq=");
      out.print(seq);
      out.write("&cpage=");
      out.print(cpage);
      out.write("'\">삭제</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn_write btn_txt01\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"cursor: pointer;\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='board_write1.jsp?seq=");
      out.print(seq);
      out.write("&cpage=");
      out.print(cpage);
      out.write("'\">쓰기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--//게시판-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 하단 디자인 -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
